# Generated by Django 3.0.6 on 2020-06-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wiki_instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='markdown文档名', max_length=50)),
                ('markdown', models.TextField(help_text='文档内容，仅支持markdown，导入markdown文件，前台自动渲染')),
            ],
        ),
    ]
