# Generated by Django 3.0.6 on 2020-05-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名字')),
                ('data_birth', models.DateField(blank=True, null=True, verbose_name='出生于')),
                ('data_death', models.DateField(blank=True, null=True, verbose_name='Died')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='输入书籍的类型(比如，python，linux，技术，非技术等等)', max_length=200, verbose_name='类别名字')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('summary', models.TextField(blank=True, help_text='丛书简介：', max_length=1000, null=True, verbose_name='简述')),
                ('isbn', models.CharField(blank=True, help_text='书籍ISBN编号', max_length=13, null=True, verbose_name='ISBN编号')),
                ('stars', models.IntegerField(blank=True, help_text='喜欢人数', null=True, verbose_name='stars')),
                ('author', models.ManyToManyField(related_name='book_author_set', to='cms.Author')),
                ('genre', models.ManyToManyField(related_name='book_genre_set', to='cms.Genre')),
            ],
        ),
    ]
