# Generated by Django 3.0.6 on 2020-05-27 14:26

import ckeditor.fields
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment', ckeditor.fields.RichTextField(help_text='评论...')),
                ('stars', models.IntegerField(blank=True, help_text='赞同人数', null=True, verbose_name='stars')),
                ('unstars', models.IntegerField(blank=True, help_text='否定人数', null=True, verbose_name='unstars')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('reply', ckeditor.fields.RichTextField(help_text='回复...')),
                ('stars', models.IntegerField(blank=True, help_text='赞同人数', null=True, verbose_name='stars')),
                ('unstars', models.IntegerField(blank=True, help_text='否定人数', null=True, verbose_name='unstars')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='标题')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('stiker', ckeditor.fields.RichTextField(blank=True, help_text='输入内容...', null=True, verbose_name='正文')),
                ('stars', models.IntegerField(blank=True, help_text='赞同人数', null=True, verbose_name='stars')),
                ('unstars', models.IntegerField(blank=True, help_text='否定人数', null=True, verbose_name='unstars')),
            ],
            options={
                'verbose_name': '贴文',
                'verbose_name_plural': '贴文',
            },
        ),
        migrations.CreateModel(
            name='StikerUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('InvitedCode', models.CharField(blank=True, max_length=100, null=True)),
                ('Gender', models.CharField(blank=True, choices=[('None', '保密'), ('Male', '男'), ('Female', '女')], max_length=7, null=True)),
                ('Icon', models.CharField(blank=True, choices=[('1', '獾'), ('2', '熊'), ('3', '小鸟'), ('4', '小猫'), ('5', '毛毛虫'), ('6', '小狗'), ('7', '麋鹿'), ('8', '牛'), ('9', '大象'), ('10', '梅花鹿'), ('11', '大猩猩'), ('12', '熊猫'), ('13', '兔子'), ('14', '鲨鱼'), ('15', '蜗牛'), ('16', '独角兽'), ('17', '鲸鱼'), ('16', '狼')], max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='话题')),
            ],
            options={
                'verbose_name': '话题',
                'verbose_name_plural': '话题',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='stiker',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_stiker_set', to='cms.StikerUser'),
        ),
        migrations.AddField(
            model_name='stiker',
            name='topics',
            field=models.ManyToManyField(related_name='topic_stikers_set', to='cms.Topic'),
        ),
        migrations.AddField(
            model_name='reply',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_replys_set', to='cms.StikerUser'),
        ),
        migrations.AddField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_replys_set', to='cms.Comment'),
        ),
        migrations.AddField(
            model_name='reply',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cms.Reply'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_comments_set', to='cms.StikerUser'),
        ),
        migrations.AddField(
            model_name='comment',
            name='stiker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stiker_comments_set', to='cms.Stiker'),
        ),
    ]
