# Generated by Django 3.0.6 on 2020-05-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20200527_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.IntegerField(blank=True, default=0, help_text='赞同人数', null=True, verbose_name='stars'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='unstars',
            field=models.IntegerField(blank=True, default=0, help_text='否定人数', null=True, verbose_name='unstars'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='stars',
            field=models.IntegerField(blank=True, default=0, help_text='赞同人数', null=True, verbose_name='stars'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='unstars',
            field=models.IntegerField(blank=True, default=0, help_text='否定人数', null=True, verbose_name='unstars'),
        ),
        migrations.AlterField(
            model_name='stiker',
            name='stars',
            field=models.IntegerField(blank=True, default=0, help_text='赞同人数', null=True, verbose_name='stars'),
        ),
        migrations.AlterField(
            model_name='stiker',
            name='unstars',
            field=models.IntegerField(blank=True, default=0, help_text='否定人数', null=True, verbose_name='unstars'),
        ),
        migrations.AlterField(
            model_name='stikeruser',
            name='Icon',
            field=models.CharField(blank=True, choices=[('1', '獾'), ('2', '熊'), ('3', '小鸟'), ('4', '小猫'), ('5', '毛毛虫'), ('6', '小狗'), ('7', '麋鹿'), ('8', '牛'), ('9', '大象'), ('10', '梅花鹿'), ('11', '大猩猩'), ('12', '熊猫'), ('13', '兔子'), ('14', '鲨鱼'), ('15', '蜗牛'), ('16', '独角兽'), ('17', '鲸鱼'), ('16', '狼')], default=1, max_length=7, null=True),
        ),
    ]
