# Generated by Django 3.0.6 on 2020-05-30 06:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_stiker_last_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='help_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='stiker',
            name='stiker',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='正文'),
        ),
    ]
