# Generated by Django 3.0.6 on 2020-05-31 01:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20200530_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='stikeruser',
            name='Introduce',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='个人说明'),
        ),
    ]
