# Generated by Django 3.0.6 on 2020-05-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_stikeruser_introduce'),
    ]

    operations = [
        migrations.AddField(
            model_name='stikeruser',
            name='Introduce_short',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
