# Generated by Django 3.0.6 on 2020-06-01 11:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_stikeruser_introduce_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stiker',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_stikers_set', to='cms.StikerUser'),
        ),
        migrations.AlterField(
            model_name='stikeruser',
            name='Introduce',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='个人说明，更加个性化的个人介绍页面'),
        ),
        migrations.AlterField(
            model_name='stikeruser',
            name='Introduce_short',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='个人简介(200字)'),
        ),
    ]
