# Generated by Django 3.0.6 on 2020-05-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_brith', models.DateField(blank=True, null=True)),
                ('data_death', models.DateField(blank=True, null=True, verbose_name='Died')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='输入书籍的类型(比如，python，linux，技术，非技术等等)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, help_text='丛书简介：', max_length=1000, null=True)),
                ('isbn', models.CharField(blank=True, help_text='书籍ISBN编号', max_length=13, null=True)),
                ('author', models.ManyToManyField(null=True, to='geek_library.Author')),
                ('genre', models.ManyToManyField(null=True, to='geek_library.Genre')),
            ],
        ),
    ]
