# Generated by Django 3.0.6 on 2020-05-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geek_library', '0002_auto_20200519_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stars',
            field=models.IntegerField(blank=True, help_text='喜欢人数', null=True),
        ),
    ]
