# Generated by Django 3.0.6 on 2020-05-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geek_library', '0003_book_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='book_author_set', to='geek_library.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='book_genre_set', to='geek_library.Genre'),
        ),
    ]
