# Generated by Django 3.0.6 on 2020-05-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geek_library', '0004_auto_20200520_0319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='data_brith',
            new_name='data_birth',
        ),
    ]
