# Generated by Django 3.0.6 on 2020-05-27 14:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geek_library', '0007_auto_20200521_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, help_text='丛书简介：', max_length=1000, null=True, verbose_name='简述'),
        ),
    ]
