# Generated by Django 3.0.6 on 2020-06-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geek_library', '0009_auto_20200602_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='short_summary',
            field=models.CharField(blank=True, help_text='丛书短简介（library页面会有显示，注意字数）：', max_length=100, null=True),
        ),
    ]
